[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"

[functions]
  directory = "functions/"

[dev]
  command = "npm run dev"
  publish = "build/"
  functions = "functions/"
  port = 8888
  targetPort = 3000
  framework = "#custom"