[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"
  framework = "svelte"

[build.environment]
  NODE_VERSION = "14"

[functions]
  directory = "functions/"

[dev]
  command = "npm run dev"
  publish = "build/"
  functions = "functions/"
  port = 8888
  targetPort = 3000
  framework = "svelte"
